### ISSUE TITLE
Lingering color issues when changing an existing paint group's color

### ISSUE THREAD

**Issue by crispconcepts** [mikinw/StickySelection#10] opened 2017-11-14 15:30 UTC
I was attempting to replicate another bug when I stumbled across this one..

I added cleared all paint groups, applied, re-opened settings for a fresh start.

I added paint group #1 (red), applied, tested, it worked fine..

I opened settings and changed the color to another swatch color (blue), applied, and saw the changes reflected in editor window immediately (entire block turned blue).

I then selected a third color choice via HSV and applied changes. The color change did not reflect in editor this time. I closed settings, pressed CTRL ALT F9, and then only some of the selection became the new color (still traces of old colors).

I tried this again and again more color is now sprinkled into the background. CTRL ALT F10, F10 does not clear all the colors. Restarting after clearing all colors does reset it finally.

![image](https://user-images.githubusercontent.com/4502605/32788254-b88b6c26-c926-11e7-8f4f-e9fcb373db81.png)

**Comment by mikinw** [comment] 2017-11-18 19:38
The root cause is the same as of #9 . So it is fixed in v2.4.

**Closed as completed by mikinw** 2017-11-18 19:38 UTC
Labels: bug
